development:
  adapter: postgresql
  database: sample_sns_development
  username: postgres
  password: oM7euDL5dorpZd9qS5CA9rRhi6gPohsL
  host: 127.0.0.1
  port: 5432



production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>