development:
  adapter: postgresql
  encoding: unicode
  database: sample_sns_development  # ← 新しいローカルDB名（自由に変えてOK）
  username: postgres                # ← ローカルPostgreSQLのユーザー名
  password: rLpo8SNki9fjMPoAUl0ClZW6Q9CI3Kgo
  host: localhost
  port: 5432
  pool: 5



production:
  primary:
    adapter: postgresql
    url: postgresql://sample_db_0t0w_user:rLpo8SNki9fjMPoAUl0ClZW6Q9CI3Kgo@dpg-cvqb371r0fns73em1q40-a.oregon-postgres.render.com/sample_db_0t0w
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

  queue:
    adapter: postgresql
    url: postgresql://sample_db_0t0w_user:rLpo8SNki9fjMPoAUl0ClZW6Q9CI3Kgo@dpg-cvqb371r0fns73em1q40-a.oregon-postgres.render.com/sample_db_0t0w
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

  cache:
    adapter: postgresql
    url: postgresql://sample_db_0t0w_user:rLpo8SNki9fjMPoAUl0ClZW6Q9CI3Kgo@dpg-cvqb371r0fns73em1q40-a.oregon-postgres.render.com/sample_db_0t0w
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
