development:
  adapter: postgresql
  database: sample_sns_development
  username: postgres
  password: oM7euDL5dorpZd9qS5CA9rRhi6gPohsL
  host: 127.0.0.1
  port: 5432



production:
  <<: *default
  host: <%= ENV["RAILS_HOST"] %>
  database: <%= ENV["RAILS_DATABASE"] %>
  username: <%= ENV["RAILS_DATABASE_USERNAME"] %>
  password: <%= ENV["RAILS_DATABASE_PASSWORD"] %>
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  charset: utf8
  collation: utf8_general_ci