development:
  adapter: postgresql
  database: sample_sns_development
  username: postgres
  password: oM7euDL5dorpZd9qS5CA9rRhi6gPohsL
  host: 127.0.0.1
  port: 5432



production:
  primary:
    adapter: postgresql
    url: postgresql://sample_sns_project2_db_user:oM7euDL5dorpZd9qS5CA9rRhi6gPohsL@dpg-d068v89r0fns73fcfm30-a.oregon-postgres.render.com/sample_sns_project2_db
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

  queue:
    adapter: postgresql
    url: postgresql://sample_sns_project2_db_user:oM7euDL5dorpZd9qS5CA9rRhi6gPohsL@dpg-d068v89r0fns73fcfm30-a.oregon-postgres.render.com/sample_sns_project2_db
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

  cache:
    adapter: postgresql
    url: postgresql://sample_sns_project2_db_user:oM7euDL5dorpZd9qS5CA9rRhi6gPohsL@dpg-d068v89r0fns73fcfm30-a.oregon-postgres.render.com/sample_sns_project2_db
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
